<div class="container kirkanta-tools-index">
  <div class="row">
    <div class="col-md-4">
      <div class="toolbox-item">
        <img src="<?= $this->basePath('/images/icons/256/x-office-address-book.png') ?>" alt="Export library addresses"/>
        <a href="<?= $this->url('kirkanta_export/library_addresses') ?>"><?= $this->tr('Library addresses') ?></a>
      </div>
    </div>
  </div>
</div>
