<h2><?= $this->tr('User profile') ?></h2>
<div class="row">
  <div class="col-md-2">
    <?= $this->gravatar($this->zfcUserIdentity()->getEmail()) ?>
  </div>
  <div class="col-md-10">
    <dl id="user-details">
      <dt><?= $this->tr('Username') ?></dt>
      <dd><?= $this->identity()->getUsername() ?></dd>
      <dt><?= $this->tr('Email') ?></dt>
      <dd><?= $this->identity()->getEmail() ?: '-' ?></dd>
      <dt><?= $this->tr('User group') ?></dt>
      <dd><?= $this->identity()->getRole()->getRoleId() ?></dd>
    </dl>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <ul id="user-actions">
      <li><a href="<?= $this->url('zfcuser/changeemail') ?>"><?= $this->tr('Change email') ?></a></li>
      <?php /* <li><a href="<?= $this->url('zfcuser/changepassword') ?>"><?= $this->tr('Change password') ?></a></li> */ ?>
    </ul>
  </div>
</div>
