<h2><?= $this->escapeHtml($organisation->getName()) ?></h2>

<ul class="nav nav-tabs">
    <li class="active"><a href="#"><?= $this->tr('Summary') ?></a></li>
    <li><a href="#"><?= $this->tr('Schedules') ?></a></li>
    <li><a href="#"><?= $this->tr('Staff') ?></a></li>
</ul>

<div class="tab">

</div>

<?php
/*
Organisation
    - Staff
    - Schedules
    - Services

    Mobile Library
        - Mobile Stops [sub organisations]
*/
